version: '3.5'

services:
  sai-front:
    # image: sai-front
    build: .
    container_name: sai-front
    ports:
      - 4001:4001
    networks:
      - proxy-reverse-networks

networks:
  proxy-reverse-networks:
    name: proxy-reverse-networks
    external: true